export enum ROUTES {
  MAIN_SCREEN = 'MAIN_SCREEN',
  START_SCREEN = 'START_SCREEN',
  SEARCH_SCREEN = 'SEARCH_SCREEN',
  DOWNLOAD_SCREEN = 'DOWNLOAD_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  PERSONAL_INFO = 'PERSONAL_INFO',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  ORDER_HISTORY_SCREEN = 'ORDER_HISTORY_SCREEN',
}
